path: ISED
train: train/images
val: val/images
test: test/images

# Classes
nc: 14 # number of classes
names:
  0: transformer
  1: current transformer
  2: oil conservator
  3: insulator
  4: post insulator
  5: tube
  6: switch
  7: clamp
  8: circuit breaker
  9: potential transformer
  10: lightning arrester
  11: wave trap
  12: capacitor
  13: reactor